// Regenerates .design-sync/ds-entry.ts, the cfg.entry barrel.
//
// Why it exists: without an entry, package-build.mjs sets
// PKG_DIR = node_modules/<pkg>, and npm never self-installs sites-project, so
// the dts resolver dies with ENOENT. An entry under .design-sync/ makes the
// resolver walk UP to the repo-root package.json, which is the PKG_DIR the rest
// of the config (srcDir, cssEntry, extraFonts) assumes.
//
// Why it is not a one-liner: two modules can export the same name. ES modules
// silently OMIT an ambiguous `export *` name rather than erroring, so the symbol
// vanishes from window.<globalName> and validate reports [BUNDLE_EXPORT]. That
// happened with `Toaster` (components/ui/{sonner,toast}.tsx). We therefore emit
// an explicit re-export for every duplicated name, resolved via componentSrcMap.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const cfg = JSON.parse(readFileSync(join(root, '.design-sync/config.json'), 'utf8'));
const map = cfg.componentSrcMap ?? {};

const files = [
  ...readdirSync(join(root, 'components')).filter((f) => f.endsWith('.tsx') && !f.endsWith('.test.tsx')).map((f) => `components/${f}`),
  ...readdirSync(join(root, 'components/ui')).filter((f) => f.endsWith('.tsx')).map((f) => `components/ui/${f}`),
];

const RX = /^export\s+(?:async\s+)?(?:function|const|class)\s+([A-Z][A-Za-z0-9]*)/gm;
const RX_BLOCK = /^export\s*\{([^}]*)\}/gms;
const owners = new Map();
for (const f of files) {
  const src = readFileSync(join(root, f), 'utf8');
  const names = new Set();
  for (const m of src.matchAll(RX)) names.add(m[1]);
  for (const b of src.matchAll(RX_BLOCK))
    for (const tok of b[1].split(',')) {
      const n = tok.trim().split(' as ').pop().trim();
      if (/^[A-Z][A-Za-z0-9]*$/.test(n)) names.add(n);
    }
  for (const n of names) owners.set(n, [...(owners.get(n) ?? []), f]);
}

const dupes = [...owners].filter(([, v]) => v.length > 1);
const lines = [
  '// design-sync entry barrel for donald-filimon-sites.',
  '// Generated by .design-sync/regen-entry.mjs - do not hand-edit.',
  '',
  '// bespoke site components',
  ...files.filter((f) => !f.includes('/ui/')).map((f) => `export * from '../${f.replace(/\.tsx$/, '')}';`),
  '',
  '// shadcn base-nova primitives',
  ...files.filter((f) => f.includes('/ui/')).map((f) => `export * from '../${f.replace(/\.tsx$/, '')}';`),
];

if (dupes.length) {
  lines.push('', '// Disambiguation: an ES `export *` collision silently DROPS the name.');
  for (const [name, mods] of dupes) {
    const pick = map[name] ?? mods[0];
    lines.push(`// ${name}: exported by ${mods.join(' and ')} - componentSrcMap picks ${pick}`);
    lines.push(`export { ${name} } from '../${String(pick).replace(/\.tsx$/, '')}';`);
  }
}

writeFileSync(join(root, '.design-sync/ds-entry.ts'), lines.join('\n') + '\n');
console.log(`ds-entry.ts: ${files.length} modules, ${dupes.length} disambiguated (${dupes.map(([n]) => n).join(', ') || 'none'})`);
